//Assignment operater
var a=10;
console.log("Assignment operater:",a)
//Arithmetic operator
var ar=20,br=10;
console.log("Assignment operater:",ar+br)
//Logical operator
console.log("Logical operater:",ar>br)
//Relational operator
console.log("Relational soperater:",ar>br)